<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickStart.Contracts\QuickStart.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Polhem.JsonRpc.Client\Polhem.JsonRpc.Client.csproj" />
    <ProjectReference Include="..\..\src\Polhem.JsonRpc.Payload\Polhem.JsonRpc.Payload.csproj" />
  </ItemGroup>

</Project>
